-- USER SQL
CREATE USER mirim3501 IDENTIFIED BY 3501  
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

-- QUOTAS

-- ROLES
GRANT DBA TO mirim3501 ;
GRANT CONNECT TO mirim3501 ;
GRANT RESOURCE TO mirim3501 ;
GRANT CREATE ANY TABLE TO mirim3501;
GRANT CREATE ANY VIEW TO mirim3501;

-- SYSTEM PRIVILEGES